site_name: dh+lib
repo_url: https://github.com/dhandlib/documentation
edit_uri: blob/master/docs
pages:
    - Home: readme.md
    - Editorial Guide:
        - "dh+lib Review": "editorial-guide/review.md"
        - "Original Features": "editorial-guide/features.md"
        - "Resources": "editorial-guide/resources.md"
        - "Series": "editorial-guide/series.md"
    - Site Specs:
        - "Hosting": "site-specs/hosting.md"
        - "WordPress": "site-specs/wordpress.md"
    - Community:
        - "History": "community/history.md"
        - "Contributors": "community/contributors.md"
    - About: about.md
theme: yeti
    
